package com.project.archives.common.dao;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;
import java.util.Arrays;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "DutyReports".
 */
@Entity(nameInDb = "DutyReports")
public class DutyReports implements Serializable{

    @Id
    @Property(nameInDb = "ID")
    private byte[] id;

    @Property(nameInDb = "UserID")
    private byte[] userID;

    @Property(nameInDb = "Name")
    private String name;

    @Property(nameInDb = "Init")
    private String init;

    @Property(nameInDb = "Position")
    private String position;

    @Property(nameInDb = "DutyReportTime")
    private String dutyReportTime;

    @Property(nameInDb = "Situation")
    private String situation;

    @Property(nameInDb = "Evaluation")
    private String evaluation;

    @Property(nameInDb = "IsDelete")
    private String isDelete;

    @Property(nameInDb = "AnnexIDStr")
    private String annexIDStr;

    @Property(nameInDb = "AddDate")
    private String addDate;

    @Property(nameInDb = "AddUser")
    private String addUser;

    @Property(nameInDb = "updateUser")
    private String updateUser;

    @Property(nameInDb = "updateDate")
    private String updateDate;

    @Property(nameInDb = "DutyReportYear")
    private String dutyReportYear;

    @Property(nameInDb = "SpecialInspectNum")
    private String specialInspectNum;

    @Property(nameInDb = "DiscoverProblemsNum")
    private String discoverProblemsNum;

    @Property(nameInDb = "InterviewNum")
    private String interviewNum;

    @Property(nameInDb = "NewSystemNum")
    private String newSystemNum;

    @Property(nameInDb = "ClueNum")
    private String clueNum;

    @Property(nameInDb = "RectificationNum")
    private String rectificationNum;

    @Property(nameInDb = "IsJoinMeeting")
    private String isJoinMeeting;

    @Property(nameInDb = "QWEvaluation")
    private String qwEvaluation;

    @Property(nameInDb = "ReviewLevel")
    private String reviewLevel;

    @Property(nameInDb = "Insufficient")
    private String insufficient;

    @Property(nameInDb = "OtherItem")
    private String otherItem;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public DutyReports() {
    }

    public DutyReports(byte[] id) {
        this.id = id;
    }

    @Generated
    public DutyReports(byte[] id, byte[] userID, String name, String init, String position, String dutyReportTime, String situation, String evaluation, String isDelete, String annexIDStr, String addDate, String addUser, String updateUser, String updateDate, String dutyReportYear, String specialInspectNum, String discoverProblemsNum, String interviewNum, String newSystemNum, String clueNum, String rectificationNum, String isJoinMeeting, String qwEvaluation, String reviewLevel, String insufficient, String otherItem) {
        this.id = id;
        this.userID = userID;
        this.name = name;
        this.init = init;
        this.position = position;
        this.dutyReportTime = dutyReportTime;
        this.situation = situation;
        this.evaluation = evaluation;
        this.isDelete = isDelete;
        this.annexIDStr = annexIDStr;
        this.addDate = addDate;
        this.addUser = addUser;
        this.updateUser = updateUser;
        this.updateDate = updateDate;
        this.dutyReportYear = dutyReportYear;
        this.specialInspectNum = specialInspectNum;
        this.discoverProblemsNum = discoverProblemsNum;
        this.interviewNum = interviewNum;
        this.newSystemNum = newSystemNum;
        this.clueNum = clueNum;
        this.rectificationNum = rectificationNum;
        this.isJoinMeeting = isJoinMeeting;
        this.qwEvaluation = qwEvaluation;
        this.reviewLevel = reviewLevel;
        this.insufficient = insufficient;
        this.otherItem = otherItem;
    }

    public byte[] getId() {
        return id;
    }

    public void setId(byte[] id) {
        this.id = id;
    }

    public byte[] getUserID() {
        return userID;
    }

    public void setUserID(byte[] userID) {
        this.userID = userID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getInit() {
        return init;
    }

    public void setInit(String init) {
        this.init = init;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getDutyReportTime() {
        return dutyReportTime;
    }

    public void setDutyReportTime(String dutyReportTime) {
        this.dutyReportTime = dutyReportTime;
    }

    public String getSituation() {
        return situation;
    }

    public void setSituation(String situation) {
        this.situation = situation;
    }

    public String getEvaluation() {
        return evaluation;
    }

    public void setEvaluation(String evaluation) {
        this.evaluation = evaluation;
    }

    public String getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    public String getAnnexIDStr() {
        return annexIDStr;
    }

    public void setAnnexIDStr(String annexIDStr) {
        this.annexIDStr = annexIDStr;
    }

    public String getAddDate() {
        return addDate;
    }

    public void setAddDate(String addDate) {
        this.addDate = addDate;
    }

    public String getAddUser() {
        return addUser;
    }

    public void setAddUser(String addUser) {
        this.addUser = addUser;
    }

    public String getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    public String getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    public String getDutyReportYear() {
        return dutyReportYear;
    }

    public void setDutyReportYear(String dutyReportYear) {
        this.dutyReportYear = dutyReportYear;
    }

    public String getSpecialInspectNum() {
        return specialInspectNum;
    }

    public void setSpecialInspectNum(String specialInspectNum) {
        this.specialInspectNum = specialInspectNum;
    }

    public String getDiscoverProblemsNum() {
        return discoverProblemsNum;
    }

    public void setDiscoverProblemsNum(String discoverProblemsNum) {
        this.discoverProblemsNum = discoverProblemsNum;
    }

    public String getInterviewNum() {
        return interviewNum;
    }

    public void setInterviewNum(String interviewNum) {
        this.interviewNum = interviewNum;
    }

    public String getNewSystemNum() {
        return newSystemNum;
    }

    public void setNewSystemNum(String newSystemNum) {
        this.newSystemNum = newSystemNum;
    }

    public String getClueNum() {
        return clueNum;
    }

    public void setClueNum(String clueNum) {
        this.clueNum = clueNum;
    }

    public String getRectificationNum() {
        return rectificationNum;
    }

    public void setRectificationNum(String rectificationNum) {
        this.rectificationNum = rectificationNum;
    }

    public String getIsJoinMeeting() {
        return isJoinMeeting;
    }

    public void setIsJoinMeeting(String isJoinMeeting) {
        this.isJoinMeeting = isJoinMeeting;
    }

    public String getQwEvaluation() {
        return qwEvaluation;
    }

    public void setQwEvaluation(String qwEvaluation) {
        this.qwEvaluation = qwEvaluation;
    }

    public String getReviewLevel() {
        return reviewLevel;
    }

    public void setReviewLevel(String reviewLevel) {
        this.reviewLevel = reviewLevel;
    }

    public String getInsufficient() {
        return insufficient;
    }

    public void setInsufficient(String insufficient) {
        this.insufficient = insufficient;
    }

    public String getOtherItem() {
        return otherItem;
    }

    public void setOtherItem(String otherItem) {
        this.otherItem = otherItem;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    @Override
    public String toString() {
        return "DutyReports{" +
                "id=" + Arrays.toString(id) +
                ", userID=" + Arrays.toString(userID) +
                ", name='" + name + '\'' +
                ", init='" + init + '\'' +
                ", position='" + position + '\'' +
                ", dutyReportTime='" + dutyReportTime + '\'' +
                ", situation='" + situation + '\'' +
                ", evaluation='" + evaluation + '\'' +
                ", isDelete='" + isDelete + '\'' +
                ", annexIDStr='" + annexIDStr + '\'' +
                ", addDate='" + addDate + '\'' +
                ", addUser='" + addUser + '\'' +
                ", updateUser='" + updateUser + '\'' +
                ", updateDate='" + updateDate + '\'' +
                ", dutyReportYear='" + dutyReportYear + '\'' +
                ", specialInspectNum='" + specialInspectNum + '\'' +
                ", discoverProblemsNum='" + discoverProblemsNum + '\'' +
                ", interviewNum='" + interviewNum + '\'' +
                ", newSystemNum='" + newSystemNum + '\'' +
                ", clueNum='" + clueNum + '\'' +
                ", rectificationNum='" + rectificationNum + '\'' +
                ", isJoinMeeting='" + isJoinMeeting + '\'' +
                ", qwEvaluation='" + qwEvaluation + '\'' +
                ", reviewLevel='" + reviewLevel + '\'' +
                ", insufficient='" + insufficient + '\'' +
                ", otherItem='" + otherItem + '\'' +
                '}';
    }
}
