package com.project.archives.common.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GiftHandDetails".
*/
public class GiftHandDetailsDao extends AbstractDao<GiftHandDetails, byte[]> {

    public static final String TABLENAME = "GiftHandDetails";

    /**
     * Properties of entity GiftHandDetails.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, byte[].class, "id", true, "ID");
        public final static Property GiftHandID = new Property(1, byte[].class, "giftHandID", false, "GiftHandID");
        public final static Property HandTime = new Property(2, String.class, "handTime", false, "HandTime");
        public final static Property HandAmount = new Property(3, Integer.class, "handAmount", false, "HandAmount");
        public final static Property HandNote = new Property(4, String.class, "handNote", false, "HandNote");
        public final static Property IsDelete = new Property(5, Integer.class, "isDelete", false, "IsDelete");
        public final static Property AddTime = new Property(6, String.class, "addTime", false, "AddTime");
    }


    public GiftHandDetailsDao(DaoConfig config) {
        super(config);
    }
    
    public GiftHandDetailsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GiftHandDetails\" (" + //
                "\"ID\" BLOB PRIMARY KEY ," + // 0: id
                "\"GiftHandID\" BLOB," + // 1: giftHandID
                "\"HandTime\" TEXT," + // 2: handTime
                "\"HandAmount\" INTEGER," + // 3: handAmount
                "\"HandNote\" TEXT," + // 4: handNote
                "\"IsDelete\" INTEGER," + // 5: isDelete
                "\"AddTime\" TEXT);"); // 6: addTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GiftHandDetails\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GiftHandDetails entity) {
        stmt.clearBindings();
 
        byte[] id = entity.getId();
        if (id != null) {
            stmt.bindBlob(1, id);
        }
 
        byte[] giftHandID = entity.getGiftHandID();
        if (giftHandID != null) {
            stmt.bindBlob(2, giftHandID);
        }
 
        String handTime = entity.getHandTime();
        if (handTime != null) {
            stmt.bindString(3, handTime);
        }
 
        Integer handAmount = entity.getHandAmount();
        if (handAmount != null) {
            stmt.bindLong(4, handAmount);
        }
 
        String handNote = entity.getHandNote();
        if (handNote != null) {
            stmt.bindString(5, handNote);
        }
 
        Integer isDelete = entity.getIsDelete();
        if (isDelete != null) {
            stmt.bindLong(6, isDelete);
        }
 
        String addTime = entity.getAddTime();
        if (addTime != null) {
            stmt.bindString(7, addTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GiftHandDetails entity) {
        stmt.clearBindings();
 
        byte[] id = entity.getId();
        if (id != null) {
            stmt.bindBlob(1, id);
        }
 
        byte[] giftHandID = entity.getGiftHandID();
        if (giftHandID != null) {
            stmt.bindBlob(2, giftHandID);
        }
 
        String handTime = entity.getHandTime();
        if (handTime != null) {
            stmt.bindString(3, handTime);
        }
 
        Integer handAmount = entity.getHandAmount();
        if (handAmount != null) {
            stmt.bindLong(4, handAmount);
        }
 
        String handNote = entity.getHandNote();
        if (handNote != null) {
            stmt.bindString(5, handNote);
        }
 
        Integer isDelete = entity.getIsDelete();
        if (isDelete != null) {
            stmt.bindLong(6, isDelete);
        }
 
        String addTime = entity.getAddTime();
        if (addTime != null) {
            stmt.bindString(7, addTime);
        }
    }

    @Override
    public byte[] readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getBlob(offset + 0);
    }    

    @Override
    public GiftHandDetails readEntity(Cursor cursor, int offset) {
        GiftHandDetails entity = new GiftHandDetails( //
            cursor.isNull(offset + 0) ? null : cursor.getBlob(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getBlob(offset + 1), // giftHandID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // handTime
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // handAmount
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // handNote
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // isDelete
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // addTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GiftHandDetails entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getBlob(offset + 0));
        entity.setGiftHandID(cursor.isNull(offset + 1) ? null : cursor.getBlob(offset + 1));
        entity.setHandTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHandAmount(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setHandNote(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIsDelete(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setAddTime(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final byte[] updateKeyAfterInsert(GiftHandDetails entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public byte[] getKey(GiftHandDetails entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GiftHandDetails entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
