package com.project.archives.common.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "GiftCards".
 */
@Entity(nameInDb = "GiftCards")
public class GiftCards {

    @Id
    @Property(nameInDb = "ID")
    private byte[] id;

    @Property(nameInDb = "GiftHandID")
    private byte[] giftHandID;

    @Property(nameInDb = "CardTime")
    private String cardTime;

    @Property(nameInDb = "CardNumber")
    private String cardNumber;

    @Property(nameInDb = "CardAmount")
    private Integer cardAmount;

    @Property(nameInDb = "CardName")
    private String cardName;

    @Property(nameInDb = "CardNote")
    private String cardNote;

    @Property(nameInDb = "IsDelete")
    private Integer isDelete;

    @Property(nameInDb = "AddTime")
    private String addTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public GiftCards() {
    }

    public GiftCards(byte[] id) {
        this.id = id;
    }

    @Generated
    public GiftCards(byte[] id, byte[] giftHandID, String cardTime, String cardNumber, Integer cardAmount, String cardName, String cardNote, Integer isDelete, String addTime) {
        this.id = id;
        this.giftHandID = giftHandID;
        this.cardTime = cardTime;
        this.cardNumber = cardNumber;
        this.cardAmount = cardAmount;
        this.cardName = cardName;
        this.cardNote = cardNote;
        this.isDelete = isDelete;
        this.addTime = addTime;
    }

    public byte[] getId() {
        return id;
    }

    public void setId(byte[] id) {
        this.id = id;
    }

    public byte[] getGiftHandID() {
        return giftHandID;
    }

    public void setGiftHandID(byte[] giftHandID) {
        this.giftHandID = giftHandID;
    }

    public String getCardTime() {
        return cardTime;
    }

    public void setCardTime(String cardTime) {
        this.cardTime = cardTime;
    }

    public String getCardNumber() {
        return cardNumber;
    }

    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    public Integer getCardAmount() {
        return cardAmount;
    }

    public void setCardAmount(Integer cardAmount) {
        this.cardAmount = cardAmount;
    }

    public String getCardName() {
        return cardName;
    }

    public void setCardName(String cardName) {
        this.cardName = cardName;
    }

    public String getCardNote() {
        return cardNote;
    }

    public void setCardNote(String cardNote) {
        this.cardNote = cardNote;
    }

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    public String getAddTime() {
        return addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
