package com.project.archives.common.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "GiftHands".
 */
@Entity(nameInDb = "GiftHands")
public class GiftHands {

    @Id
    @Property(nameInDb = "ID")
    private byte[] id;

    @Property(nameInDb = "UserID")
    private byte[] userID;

    @Property(nameInDb = "Name")
    private String name;

    @Property(nameInDb = "Init")
    private String init;

    @Property(nameInDb = "Position")
    private String position;

    @Property(nameInDb = "Rank")
    private Integer rank;

    @Property(nameInDb = "IsDelete")
    private Integer isDelete;

    @Property(nameInDb = "AddDate")
    private String addDate;

    @Property(nameInDb = "AddUser")
    private String addUser;

    @Property(nameInDb = "UpdateDate")
    private String updateDate;

    @Property(nameInDb = "UpdateUser")
    private String updateUser;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public GiftHands() {
    }

    public GiftHands(byte[] id) {
        this.id = id;
    }

    @Generated
    public GiftHands(byte[] id, byte[] userID, String name, String init, String position, Integer rank, Integer isDelete, String addDate, String addUser, String updateDate, String updateUser) {
        this.id = id;
        this.userID = userID;
        this.name = name;
        this.init = init;
        this.position = position;
        this.rank = rank;
        this.isDelete = isDelete;
        this.addDate = addDate;
        this.addUser = addUser;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
    }

    public byte[] getId() {
        return id;
    }

    public void setId(byte[] id) {
        this.id = id;
    }

    public byte[] getUserID() {
        return userID;
    }

    public void setUserID(byte[] userID) {
        this.userID = userID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getInit() {
        return init;
    }

    public void setInit(String init) {
        this.init = init;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public Integer getRank() {
        return rank;
    }

    public void setRank(Integer rank) {
        this.rank = rank;
    }

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    public String getAddDate() {
        return addDate;
    }

    public void setAddDate(String addDate) {
        this.addDate = addDate;
    }

    public String getAddUser() {
        return addUser;
    }

    public void setAddUser(String addUser) {
        this.addUser = addUser;
    }

    public String getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    public String getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
