package com.project.archives.common.dao;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MULTI_DICTIONARIES".
 */
@Entity
public class MultiDictionaries implements Serializable {

    @Id
    private byte[] ID;
    private String OptionsName;
    private Integer Type;
    private Integer Sort;
    private Integer IsDelete;
    private java.util.Date AddDate;
    private String AddUser;
    private java.util.Date UpdateDate;
    private String UpdateUser;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 1978367645)
    public MultiDictionaries() {
    }

    public MultiDictionaries(byte[] ID) {
        this.ID = ID;
    }

    @Generated(hash = 1017756176)
    public MultiDictionaries(byte[] ID, String OptionsName, Integer Type, Integer Sort, Integer IsDelete, java.util.Date AddDate, String AddUser, java.util.Date UpdateDate, String UpdateUser) {
        this.ID = ID;
        this.OptionsName = OptionsName;
        this.Type = Type;
        this.Sort = Sort;
        this.IsDelete = IsDelete;
        this.AddDate = AddDate;
        this.AddUser = AddUser;
        this.UpdateDate = UpdateDate;
        this.UpdateUser = UpdateUser;
    }

    public byte[] getID() {
        return ID;
    }

    public void setID(byte[] ID) {
        this.ID = ID;
    }

    public String getOptionsName() {
        return OptionsName;
    }

    public void setOptionsName(String OptionsName) {
        this.OptionsName = OptionsName;
    }

    public Integer getType() {
        return Type;
    }

    public void setType(Integer Type) {
        this.Type = Type;
    }

    public Integer getSort() {
        return Sort;
    }

    public void setSort(Integer Sort) {
        this.Sort = Sort;
    }

    public Integer getIsDelete() {
        return IsDelete;
    }

    public void setIsDelete(Integer IsDelete) {
        this.IsDelete = IsDelete;
    }

    public java.util.Date getAddDate() {
        return AddDate;
    }

    public void setAddDate(java.util.Date AddDate) {
        this.AddDate = AddDate;
    }

    public String getAddUser() {
        return AddUser;
    }

    public void setAddUser(String AddUser) {
        this.AddUser = AddUser;
    }

    public java.util.Date getUpdateDate() {
        return UpdateDate;
    }

    public void setUpdateDate(java.util.Date UpdateDate) {
        this.UpdateDate = UpdateDate;
    }

    public String getUpdateUser() {
        return UpdateUser;
    }

    public void setUpdateUser(String UpdateUser) {
        this.UpdateUser = UpdateUser;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
