package com.project.archives.common.dao;

import org.greenrobot.greendao.annotation.*;

import java.util.Arrays;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "VERIFICATIONS".
 */
@Entity
public class Verifications {

    @Id
    private byte[] ID;
    private byte[] UserID;
    private String Name;
    private String Init;
    private String Position;
    private Integer Rank;
    private Integer Coding;
    private Integer IsObject;
    private Integer IsOfficer;
    private byte[] Discipline;
    private Integer Organ;
    private java.util.Date VerificTime;
    private java.util.Date TakingTime;
    private String Clues;
    private String VerificResult;
    private Integer TakingResult;
    private Integer ResultSituation;
    private String Note;
    private byte[] AnnexIDStr;
    private Integer isDelete;
    private java.util.Date AddDate;
    private String AddUser;
    private java.util.Date UpdateDate;
    private String UpdateUser;
    private Integer objectSource;
    private java.util.Date ProcessTime;
    private String Trail;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 485589158)
    public Verifications() {
    }

    public Verifications(byte[] ID) {
        this.ID = ID;
    }

    @Generated(hash = 1184866260)
    public Verifications(byte[] ID, byte[] UserID, String Name, String Init, String Position, Integer Rank, Integer Coding, Integer IsObject, Integer IsOfficer, byte[] Discipline, Integer Organ, java.util.Date VerificTime, java.util.Date TakingTime, String Clues, String VerificResult, Integer TakingResult, Integer ResultSituation, String Note, byte[] AnnexIDStr, Integer isDelete, java.util.Date AddDate, String AddUser, java.util.Date UpdateDate, String UpdateUser, Integer objectSource, java.util.Date ProcessTime, String Trail) {
        this.ID = ID;
        this.UserID = UserID;
        this.Name = Name;
        this.Init = Init;
        this.Position = Position;
        this.Rank = Rank;
        this.Coding = Coding;
        this.IsObject = IsObject;
        this.IsOfficer = IsOfficer;
        this.Discipline = Discipline;
        this.Organ = Organ;
        this.VerificTime = VerificTime;
        this.TakingTime = TakingTime;
        this.Clues = Clues;
        this.VerificResult = VerificResult;
        this.TakingResult = TakingResult;
        this.ResultSituation = ResultSituation;
        this.Note = Note;
        this.AnnexIDStr = AnnexIDStr;
        this.isDelete = isDelete;
        this.AddDate = AddDate;
        this.AddUser = AddUser;
        this.UpdateDate = UpdateDate;
        this.UpdateUser = UpdateUser;
        this.objectSource = objectSource;
        this.ProcessTime = ProcessTime;
        this.Trail = Trail;
    }

    public byte[] getID() {
        return ID;
    }

    public void setID(byte[] ID) {
        this.ID = ID;
    }

    public byte[] getUserID() {
        return UserID;
    }

    public void setUserID(byte[] UserID) {
        this.UserID = UserID;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getInit() {
        return Init;
    }

    public void setInit(String Init) {
        this.Init = Init;
    }

    public String getPosition() {
        return Position;
    }

    public void setPosition(String Position) {
        this.Position = Position;
    }

    public Integer getRank() {
        return Rank;
    }

    public void setRank(Integer Rank) {
        this.Rank = Rank;
    }

    public Integer getCoding() {
        return Coding;
    }

    public void setCoding(Integer Coding) {
        this.Coding = Coding;
    }

    public Integer getIsObject() {
        return IsObject;
    }

    public void setIsObject(Integer IsObject) {
        this.IsObject = IsObject;
    }

    public Integer getIsOfficer() {
        return IsOfficer;
    }

    public void setIsOfficer(Integer IsOfficer) {
        this.IsOfficer = IsOfficer;
    }

    public byte[] getDiscipline() {
        return Discipline;
    }

    public void setDiscipline(byte[] Discipline) {
        this.Discipline = Discipline;
    }

    public Integer getOrgan() {
        return Organ;
    }

    public void setOrgan(Integer Organ) {
        this.Organ = Organ;
    }

    public java.util.Date getVerificTime() {
        return VerificTime;
    }

    public void setVerificTime(java.util.Date VerificTime) {
        this.VerificTime = VerificTime;
    }

    public java.util.Date getTakingTime() {
        return TakingTime;
    }

    public void setTakingTime(java.util.Date TakingTime) {
        this.TakingTime = TakingTime;
    }

    public String getClues() {
        return Clues;
    }

    public void setClues(String Clues) {
        this.Clues = Clues;
    }

    public String getVerificResult() {
        return VerificResult;
    }

    public void setVerificResult(String VerificResult) {
        this.VerificResult = VerificResult;
    }

    public Integer getTakingResult() {
        return TakingResult;
    }

    public void setTakingResult(Integer TakingResult) {
        this.TakingResult = TakingResult;
    }

    public Integer getResultSituation() {
        return ResultSituation;
    }

    public void setResultSituation(Integer ResultSituation) {
        this.ResultSituation = ResultSituation;
    }

    public String getNote() {
        return Note;
    }

    public void setNote(String Note) {
        this.Note = Note;
    }

    public byte[] getAnnexIDStr() {
        return AnnexIDStr;
    }

    public void setAnnexIDStr(byte[] AnnexIDStr) {
        this.AnnexIDStr = AnnexIDStr;
    }

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    public java.util.Date getAddDate() {
        return AddDate;
    }

    public void setAddDate(java.util.Date AddDate) {
        this.AddDate = AddDate;
    }

    public String getAddUser() {
        return AddUser;
    }

    public void setAddUser(String AddUser) {
        this.AddUser = AddUser;
    }

    public java.util.Date getUpdateDate() {
        return UpdateDate;
    }

    public void setUpdateDate(java.util.Date UpdateDate) {
        this.UpdateDate = UpdateDate;
    }

    public String getUpdateUser() {
        return UpdateUser;
    }

    public void setUpdateUser(String UpdateUser) {
        this.UpdateUser = UpdateUser;
    }

    public Integer getObjectSource() {
        return objectSource;
    }

    public void setObjectSource(Integer objectSource) {
        this.objectSource = objectSource;
    }

    public java.util.Date getProcessTime() {
        return ProcessTime;
    }

    public void setProcessTime(java.util.Date ProcessTime) {
        this.ProcessTime = ProcessTime;
    }

    public String getTrail() {
        return Trail;
    }

    public void setTrail(String Trail) {
        this.Trail = Trail;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    @Override
    public String toString() {
        return "Verifications{" +
                "ID=" + Arrays.toString(ID) +
                ", UserID=" + Arrays.toString(UserID) +
                ", Name='" + Name + '\'' +
                ", Init='" + Init + '\'' +
                ", Position='" + Position + '\'' +
                ", Rank=" + Rank +
                ", Coding=" + Coding +
                ", IsObject=" + IsObject +
                ", IsOfficer=" + IsOfficer +
                ", Discipline=" + Arrays.toString(Discipline) +
                ", Organ=" + Organ +
                ", VerificTime=" + VerificTime +
                ", TakingTime=" + TakingTime +
                ", Clues='" + Clues + '\'' +
                ", VerificResult='" + VerificResult + '\'' +
                ", TakingResult=" + TakingResult +
                ", ResultSituation=" + ResultSituation +
                ", Note='" + Note + '\'' +
                ", AnnexIDStr=" + Arrays.toString(AnnexIDStr) +
                ", isDelete=" + isDelete +
                ", AddDate=" + AddDate +
                ", AddUser='" + AddUser + '\'' +
                ", UpdateDate=" + UpdateDate +
                ", UpdateUser='" + UpdateUser + '\'' +
                ", objectSource=" + objectSource +
                ", ProcessTime=" + ProcessTime +
                ", Trail='" + Trail + '\'' +
                '}';
    }
}
